language: php
php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm
sudo: false
before_install:
  - composer self-update
install:
  - composer install
before_script:
  - phpenv config-rm xdebug.ini
script:
  - phpunit
addons:
  code_climate:
    repo_token: 44e7b241ad59ec2f8e67b242b344e5f9b96d3b99d6246816593392a5f6386b53